"""empty message

Revision ID: 0b2ec7a5bc1d
Revises: 62ba3ccbe50a
Create Date: 2024-04-12 09:00:40.358314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2ec7a5bc1d'
down_revision = '62ba3ccbe50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
