"""empty message

Revision ID: 436556e45432
Revises: 8d2cb03a505f
Create Date: 2024-04-12 08:50:11.004852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436556e45432'
down_revision = '8d2cb03a505f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
