"""empty message

Revision ID: 5d019e22635e
Revises: 51c1cad81226
Create Date: 2024-03-22 02:53:04.241220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d019e22635e'
down_revision = '51c1cad81226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
