"""empty message

Revision ID: 62ba3ccbe50a
Revises: 436556e45432
Create Date: 2024-04-12 08:58:11.319534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ba3ccbe50a'
down_revision = '436556e45432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
