"""empty message

Revision ID: 73f9ffe15e2c
Revises: d00d3e53ec10
Create Date: 2024-03-22 03:15:49.422497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f9ffe15e2c'
down_revision = 'd00d3e53ec10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
