"""empty message

Revision ID: 8d2cb03a505f
Revises: ffaaa5b07619
Create Date: 2024-04-12 06:56:06.482006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2cb03a505f'
down_revision = 'ffaaa5b07619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
