"""empty message

Revision ID: a9102595c63f
Revises: 5d019e22635e
Create Date: 2024-03-22 03:14:18.419932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9102595c63f'
down_revision = '5d019e22635e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
