"""empty message

Revision ID: a9b1c53119b0
Revises: de6d57f30791
Create Date: 2024-03-21 15:00:46.165214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b1c53119b0'
down_revision = 'de6d57f30791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
