"""empty message

Revision ID: d7ad7490c8c5
Revises: e3ddeac08097
Create Date: 2024-04-12 11:00:36.343536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ad7490c8c5'
down_revision = 'e3ddeac08097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
