"""empty message

Revision ID: e3ddeac08097
Revises: 0b2ec7a5bc1d
Create Date: 2024-04-12 10:59:34.697310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ddeac08097'
down_revision = '0b2ec7a5bc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starttime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('endtime', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('endtime')
        batch_op.drop_column('starttime')

    # ### end Alembic commands ###
